//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: serverdata.proto
namespace serverdata
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BufferData")]
  public partial class BufferData : global::ProtoBuf.IExtensible
  {
    public BufferData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BufferList")]
  public partial class BufferList : global::ProtoBuf.IExtensible
  {
    public BufferList() {}
    
    private readonly global::System.Collections.Generic.List<BufferData> _data = new global::System.Collections.Generic.List<BufferData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BufferData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterData")]
  public partial class CharacterData : global::ProtoBuf.IExtensible
  {
    public CharacterData() {}
    
    private int _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _speed;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _attackspeed;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"attackspeed", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int attackspeed
    {
      get { return _attackspeed; }
      set { _attackspeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterList")]
  public partial class CharacterList : global::ProtoBuf.IExtensible
  {
    public CharacterList() {}
    
    private readonly global::System.Collections.Generic.List<CharacterData> _data = new global::System.Collections.Generic.List<CharacterData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CharacterData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ComposeData")]
  public partial class ComposeData : global::ProtoBuf.IExtensible
  {
    public ComposeData() {}
    
    private int _itemid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private int _element_first;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"element_first", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int element_first
    {
      get { return _element_first; }
      set { _element_first = value; }
    }
    private int _element_first_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"element_first_num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int element_first_num
    {
      get { return _element_first_num; }
      set { _element_first_num = value; }
    }
    private int _element_second;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"element_second", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int element_second
    {
      get { return _element_second; }
      set { _element_second = value; }
    }
    private int _element_second_num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"element_second_num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int element_second_num
    {
      get { return _element_second_num; }
      set { _element_second_num = value; }
    }
    private int _element_third;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"element_third", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int element_third
    {
      get { return _element_third; }
      set { _element_third = value; }
    }
    private int _element_third_num;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"element_third_num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int element_third_num
    {
      get { return _element_third_num; }
      set { _element_third_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ComposeList")]
  public partial class ComposeList : global::ProtoBuf.IExtensible
  {
    public ComposeList() {}
    
    private readonly global::System.Collections.Generic.List<ComposeData> _data = new global::System.Collections.Generic.List<ComposeData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ComposeData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipData")]
  public partial class EquipData : global::ProtoBuf.IExtensible
  {
    public EquipData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _group_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private int _group_index;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"group_index", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int group_index
    {
      get { return _group_index; }
      set { _group_index = value; }
    }
    private int _quality;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _skillid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _att_space;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"att_space", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int att_space
    {
      get { return _att_space; }
      set { _att_space = value; }
    }
    private int _fallback;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"fallback", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int fallback
    {
      get { return _fallback; }
      set { _fallback = value; }
    }
    private int _move;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"move", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int move
    {
      get { return _move; }
      set { _move = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _armor;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"armor", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int armor
    {
      get { return _armor; }
      set { _armor = value; }
    }
    private int _damage_add;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"damage_add", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int damage_add
    {
      get { return _damage_add; }
      set { _damage_add = value; }
    }
    private int _hp_add;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"hp_add", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hp_add
    {
      get { return _hp_add; }
      set { _hp_add = value; }
    }
    private int _att_speed_add;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"att_speed_add", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int att_speed_add
    {
      get { return _att_speed_add; }
      set { _att_speed_add = value; }
    }
    private int _move_add;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"move_add", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int move_add
    {
      get { return _move_add; }
      set { _move_add = value; }
    }
    private int _crit;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int crit
    {
      get { return _crit; }
      set { _crit = value; }
    }
    private int _crit_dmg;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"crit_dmg", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int crit_dmg
    {
      get { return _crit_dmg; }
      set { _crit_dmg = value; }
    }
    private int _strenthstuff_first;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"strenthstuff_first", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int strenthstuff_first
    {
      get { return _strenthstuff_first; }
      set { _strenthstuff_first = value; }
    }
    private int _strenthstuff_second;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"strenthstuff_second", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int strenthstuff_second
    {
      get { return _strenthstuff_second; }
      set { _strenthstuff_second = value; }
    }
    private int _strenthstuff_third;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"strenthstuff_third", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int strenthstuff_third
    {
      get { return _strenthstuff_third; }
      set { _strenthstuff_third = value; }
    }
    private int _strenthstuff_fourth;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"strenthstuff_fourth", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int strenthstuff_fourth
    {
      get { return _strenthstuff_fourth; }
      set { _strenthstuff_fourth = value; }
    }
    private int _strenthstuff_fifth;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"strenthstuff_fifth", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int strenthstuff_fifth
    {
      get { return _strenthstuff_fifth; }
      set { _strenthstuff_fifth = value; }
    }
    private int _strenthstuff_sixth;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"strenthstuff_sixth", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int strenthstuff_sixth
    {
      get { return _strenthstuff_sixth; }
      set { _strenthstuff_sixth = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipList")]
  public partial class EquipList : global::ProtoBuf.IExtensible
  {
    public EquipList() {}
    
    private readonly global::System.Collections.Generic.List<EquipData> _data = new global::System.Collections.Generic.List<EquipData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipGroupData")]
  public partial class EquipGroupData : global::ProtoBuf.IExtensible
  {
    public EquipGroupData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _type_eqp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type_eqp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int type_eqp
    {
      get { return _type_eqp; }
      set { _type_eqp = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipGroupList")]
  public partial class EquipGroupList : global::ProtoBuf.IExtensible
  {
    public EquipGroupList() {}
    
    private readonly global::System.Collections.Generic.List<EquipGroupData> _data = new global::System.Collections.Generic.List<EquipGroupData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipGroupData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemData")]
  public partial class ItemData : global::ProtoBuf.IExtensible
  {
    public ItemData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _itemquality;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemquality", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemquality
    {
      get { return _itemquality; }
      set { _itemquality = value; }
    }
    private int _itemtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"itemtype", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemtype
    {
      get { return _itemtype; }
      set { _itemtype = value; }
    }
    private int _pile;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pile", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int pile
    {
      get { return _pile; }
      set { _pile = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _price;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private int _chestid;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"chestid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int chestid
    {
      get { return _chestid; }
      set { _chestid = value; }
    }
    private int _buffid;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"buffid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int buffid
    {
      get { return _buffid; }
      set { _buffid = value; }
    }
    private int _state_type;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"state_type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int state_type
    {
      get { return _state_type; }
      set { _state_type = value; }
    }
    private int _state_value;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"state_value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int state_value
    {
      get { return _state_value; }
      set { _state_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemList")]
  public partial class ItemList : global::ProtoBuf.IExtensible
  {
    public ItemList() {}
    
    private readonly global::System.Collections.Generic.List<ItemData> _data = new global::System.Collections.Generic.List<ItemData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ItemData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LangData")]
  public partial class LangData : global::ProtoBuf.IExtensible
  {
    public LangData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LangList")]
  public partial class LangList : global::ProtoBuf.IExtensible
  {
    public LangList() {}
    
    private readonly global::System.Collections.Generic.List<LangData> _data = new global::System.Collections.Generic.List<LangData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LangData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterData")]
  public partial class MonsterData : global::ProtoBuf.IExtensible
  {
    public MonsterData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _hpCounter;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hpCounter", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hpCounter
    {
      get { return _hpCounter; }
      set { _hpCounter = value; }
    }
    private int _speed;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private byte[] _view;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"view", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] view
    {
      get { return _view; }
      set { _view = value; }
    }
    private byte[] _luascript;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"luascript", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] luascript
    {
      get { return _luascript; }
      set { _luascript = value; }
    }
    private int _defaultSkill;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"defaultSkill", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int defaultSkill
    {
      get { return _defaultSkill; }
      set { _defaultSkill = value; }
    }
    private byte[] _appearEffect;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"appearEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] appearEffect
    {
      get { return _appearEffect; }
      set { _appearEffect = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterList")]
  public partial class MonsterList : global::ProtoBuf.IExtensible
  {
    public MonsterList() {}
    
    private readonly global::System.Collections.Generic.List<MonsterData> _data = new global::System.Collections.Generic.List<MonsterData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MonsterData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonstertableData")]
  public partial class MonstertableData : global::ProtoBuf.IExtensible
  {
    public MonstertableData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _monsterid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"monsterid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> monsterid
    {
      get { return _monsterid; }
    }
  
    private int _dropid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dropid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int dropid
    {
      get { return _dropid; }
      set { _dropid = value; }
    }
    private int _rate;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonstertableList")]
  public partial class MonstertableList : global::ProtoBuf.IExtensible
  {
    public MonstertableList() {}
    
    private readonly global::System.Collections.Generic.List<MonstertableData> _data = new global::System.Collections.Generic.List<MonstertableData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MonstertableData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PetBaseData")]
  public partial class PetBaseData : global::ProtoBuf.IExtensible
  {
    public PetBaseData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _groupid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"groupid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int groupid
    {
      get { return _groupid; }
      set { _groupid = value; }
    }
    private int _stars;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"stars", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int stars
    {
      get { return _stars; }
      set { _stars = value; }
    }
    private int _baseprice;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"baseprice", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int baseprice
    {
      get { return _baseprice; }
      set { _baseprice = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _damage_grow;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"damage_grow", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int damage_grow
    {
      get { return _damage_grow; }
      set { _damage_grow = value; }
    }
    private int _state_type;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"state_type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int state_type
    {
      get { return _state_type; }
      set { _state_type = value; }
    }
    private int _state_base;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"state_base", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int state_base
    {
      get { return _state_base; }
      set { _state_base = value; }
    }
    private int _state_grow;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"state_grow", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int state_grow
    {
      get { return _state_grow; }
      set { _state_grow = value; }
    }
    private int _skill_first;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"skill_first", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int skill_first
    {
      get { return _skill_first; }
      set { _skill_first = value; }
    }
    private int _skill_first_con;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"skill_first_con", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int skill_first_con
    {
      get { return _skill_first_con; }
      set { _skill_first_con = value; }
    }
    private int _skill_second;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"skill_second", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int skill_second
    {
      get { return _skill_second; }
      set { _skill_second = value; }
    }
    private int _skill_second_con;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"skill_second_con", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int skill_second_con
    {
      get { return _skill_second_con; }
      set { _skill_second_con = value; }
    }
    private int _skill_third;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"skill_third", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int skill_third
    {
      get { return _skill_third; }
      set { _skill_third = value; }
    }
    private int _skill_third_con;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"skill_third_con", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int skill_third_con
    {
      get { return _skill_third_con; }
      set { _skill_third_con = value; }
    }
    private int _itemid_first;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"itemid_first", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemid_first
    {
      get { return _itemid_first; }
      set { _itemid_first = value; }
    }
    private int _itemid_first_num;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"itemid_first_num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemid_first_num
    {
      get { return _itemid_first_num; }
      set { _itemid_first_num = value; }
    }
    private int _itemid_second;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"itemid_second", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemid_second
    {
      get { return _itemid_second; }
      set { _itemid_second = value; }
    }
    private int _itemid_second_num;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"itemid_second_num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemid_second_num
    {
      get { return _itemid_second_num; }
      set { _itemid_second_num = value; }
    }
    private int _itemid_third;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"itemid_third", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemid_third
    {
      get { return _itemid_third; }
      set { _itemid_third = value; }
    }
    private int _itemid_third_num;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"itemid_third_num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int itemid_third_num
    {
      get { return _itemid_third_num; }
      set { _itemid_third_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PetBaseList")]
  public partial class PetBaseList : global::ProtoBuf.IExtensible
  {
    public PetBaseList() {}
    
    private readonly global::System.Collections.Generic.List<PetBaseData> _data = new global::System.Collections.Generic.List<PetBaseData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PetBaseData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PetLevelupData")]
  public partial class PetLevelupData : global::ProtoBuf.IExtensible
  {
    public PetLevelupData() {}
    
    private int _lv;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _petstate_grew;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"petstate_grew", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int petstate_grew
    {
      get { return _petstate_grew; }
      set { _petstate_grew = value; }
    }
    private int _petstrenth_cost;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"petstrenth_cost", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int petstrenth_cost
    {
      get { return _petstrenth_cost; }
      set { _petstrenth_cost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PetLevelupList")]
  public partial class PetLevelupList : global::ProtoBuf.IExtensible
  {
    public PetLevelupList() {}
    
    private readonly global::System.Collections.Generic.List<PetLevelupData> _data = new global::System.Collections.Generic.List<PetLevelupData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PetLevelupData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PetUnlockData")]
  public partial class PetUnlockData : global::ProtoBuf.IExtensible
  {
    public PetUnlockData() {}
    
    private int _groupid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int groupid
    {
      get { return _groupid; }
      set { _groupid = value; }
    }
    private int _unlockcase_first;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unlockcase_first", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int unlockcase_first
    {
      get { return _unlockcase_first; }
      set { _unlockcase_first = value; }
    }
    private int _unlockcase_first_value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"unlockcase_first_value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int unlockcase_first_value
    {
      get { return _unlockcase_first_value; }
      set { _unlockcase_first_value = value; }
    }
    private int _unlockcase_second;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"unlockcase_second", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int unlockcase_second
    {
      get { return _unlockcase_second; }
      set { _unlockcase_second = value; }
    }
    private int _unlockcase_second_value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"unlockcase_second_value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int unlockcase_second_value
    {
      get { return _unlockcase_second_value; }
      set { _unlockcase_second_value = value; }
    }
    private int _unlockcost_type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"unlockcost_type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int unlockcost_type
    {
      get { return _unlockcost_type; }
      set { _unlockcost_type = value; }
    }
    private int _unlockcost_type_value;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"unlockcost_type_value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int unlockcost_type_value
    {
      get { return _unlockcost_type_value; }
      set { _unlockcost_type_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PetUnlockList")]
  public partial class PetUnlockList : global::ProtoBuf.IExtensible
  {
    public PetUnlockList() {}
    
    private readonly global::System.Collections.Generic.List<PetUnlockData> _data = new global::System.Collections.Generic.List<PetUnlockData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PetUnlockData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillData")]
  public partial class SkillData : global::ProtoBuf.IExtensible
  {
    public SkillData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _hitvalue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hitvalue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hitvalue
    {
      get { return _hitvalue; }
      set { _hitvalue = value; }
    }
    private int _range;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"range", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int range
    {
      get { return _range; }
      set { _range = value; }
    }
    private int _bullettype;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"bullettype", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int bullettype
    {
      get { return _bullettype; }
      set { _bullettype = value; }
    }
    private int _shootspeed;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"shootspeed", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int shootspeed
    {
      get { return _shootspeed; }
      set { _shootspeed = value; }
    }
    private int _bulletspeed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"bulletspeed", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int bulletspeed
    {
      get { return _bulletspeed; }
      set { _bulletspeed = value; }
    }
    private byte[] _expsffect;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"expsffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] expsffect
    {
      get { return _expsffect; }
      set { _expsffect = value; }
    }
    private int _selfbuffer1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"selfbuffer1", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int selfbuffer1
    {
      get { return _selfbuffer1; }
      set { _selfbuffer1 = value; }
    }
    private int _selfbuffer2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"selfbuffer2", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int selfbuffer2
    {
      get { return _selfbuffer2; }
      set { _selfbuffer2 = value; }
    }
    private int _hitbuffer1;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"hitbuffer1", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hitbuffer1
    {
      get { return _hitbuffer1; }
      set { _hitbuffer1 = value; }
    }
    private int _hitbuffer2;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"hitbuffer2", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hitbuffer2
    {
      get { return _hitbuffer2; }
      set { _hitbuffer2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillList")]
  public partial class SkillList : global::ProtoBuf.IExtensible
  {
    public SkillList() {}
    
    private readonly global::System.Collections.Generic.List<SkillData> _data = new global::System.Collections.Generic.List<SkillData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StrenthData")]
  public partial class StrenthData : global::ProtoBuf.IExtensible
  {
    public StrenthData() {}
    
    private int _strenthlevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"strenthlevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int strenthlevel
    {
      get { return _strenthlevel; }
      set { _strenthlevel = value; }
    }
    private int _damageup;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damageup", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int damageup
    {
      get { return _damageup; }
      set { _damageup = value; }
    }
    private int _hpup;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hpup", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int hpup
    {
      get { return _hpup; }
      set { _hpup = value; }
    }
    private int _armorup;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"armorup", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int armorup
    {
      get { return _armorup; }
      set { _armorup = value; }
    }
    private int _strenthcost;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"strenthcost", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int strenthcost
    {
      get { return _strenthcost; }
      set { _strenthcost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StrenthList")]
  public partial class StrenthList : global::ProtoBuf.IExtensible
  {
    public StrenthList() {}
    
    private readonly global::System.Collections.Generic.List<StrenthData> _data = new global::System.Collections.Generic.List<StrenthData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StrenthData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneData")]
  public partial class ZoneData : global::ProtoBuf.IExtensible
  {
    public ZoneData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _prezone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"prezone", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int prezone
    {
      get { return _prezone; }
      set { _prezone = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _dropid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"dropid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int dropid
    {
      get { return _dropid; }
      set { _dropid = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _monstertable = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"monstertable", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> monstertable
    {
      get { return _monstertable; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneList")]
  public partial class ZoneList : global::ProtoBuf.IExtensible
  {
    public ZoneList() {}
    
    private readonly global::System.Collections.Generic.List<ZoneData> _data = new global::System.Collections.Generic.List<ZoneData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ZoneData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}